namespace SapphTools.DHA.Stig.Common.Enums;
[Flags]
internal enum RightsAccessMask : uint {
    SPECIFIC_RIGHTS_ALL      = 0x0000FFFF,
    DELETE                   = 0x00010000,
    READ_CONTROL             = 0x00020000,
    WRITE_DAC                = 0x00040000,
    WRITE_OWNER              = 0x00080000,
    SYNCHRONIZE              = 0x00100000,
    STANDARD_RIGHTS_REQUIRED = DELETE | READ_CONTROL | WRITE_DAC | WRITE_OWNER,
    STANDARD_RIGHTS_ALL      = SYNCHRONIZE | STANDARD_RIGHTS_REQUIRED,
    ACCESS_SYSTEM_SECURITY   = 0x01000000,
    MAXIMUM_ALLOWED          = 0x02000000,
    GENERIC_ALL              = 0x10000000,
    GENERIC_EXECUTE          = 0x20000000,
    GENERIC_WRITE            = 0x40000000,
    GENERIC_READ             = 0x80000000
}
[Flags]
internal enum FileAccessMask : uint {
    //Shared Masks
    FILE_READ_DATA            = 0x00000001,
    FILE_WRITE_DATA           = 0x00000002,
    FILE_APPEND_DATA          = 0x00000004,
    FILE_TRAVERSE             = 0x00000020,
    FILE_READ_ATTRIBUTES      = 0x00000080,
    FILE_WRITE_ATTRIBUTES     = 0x00000100,
    FILE_SPECIFIC_READ_ALL    = FILE_READ_DATA | FILE_READ_ATTRIBUTES | FILE_READ_EA,
    FILE_SPECIFIC_WRITE_ALL   = FILE_WRITE_DATA | FILE_APPEND_DATA | FILE_WRITE_EA | FILE_WRITE_ATTRIBUTES,
    FILE_SPECIFIC_EXECUTE_ALL = FILE_READ_ATTRIBUTES | FILE_TRAVERSE,
    FILE_SPECIFIC_RIGHTS_ALL  = FILE_SPECIFIC_READ_ALL | FILE_SPECIFIC_WRITE_ALL | FILE_SPECIFIC_EXECUTE_ALL | FILE_DELETE_CHILD,
    DELETE                    = RightsAccessMask.DELETE,
    READ_CONTROL              = RightsAccessMask.READ_CONTROL,
    STANDARD_RIGHTS_READ      = READ_CONTROL,
    STANDARD_RIGHTS_WRITE     = READ_CONTROL,
    STANDARD_RIGHTS_EXECUTE   = READ_CONTROL,
    FILE_GENERIC_READ         = FILE_SPECIFIC_READ_ALL | READ_CONTROL | SYNCHRONIZE,
    FILE_GENERIC_WRITE        = FILE_SPECIFIC_WRITE_ALL | READ_CONTROL | SYNCHRONIZE,
    FILE_GENERIC_EXECUTE      = FILE_SPECIFIC_EXECUTE_ALL | READ_CONTROL | SYNCHRONIZE,
    WRITE_DAC                 = RightsAccessMask.WRITE_DAC,
    WRITE_OWNER               = RightsAccessMask.WRITE_OWNER,
    SYNCHRONIZE               = RightsAccessMask.SYNCHRONIZE,
    FILE_ALL_ACCESS           = RightsAccessMask.STANDARD_RIGHTS_ALL | FILE_SPECIFIC_RIGHTS_ALL, 
    //Directory Masks
    FILE_LIST_DIRECTORY       = FILE_READ_DATA,
    FILE_ADD_FILE             = FILE_WRITE_DATA,
    FILE_ADD_SUBDIRECTORY     = FILE_APPEND_DATA,
    FILE_DELETE_CHILD         = 0x00000040,
    //File Masks
    FILE_READ_EA              = 0x00000008,
    FILE_WRITE_EA             = 0x00000010,
    FILE_EXECUTE              = FILE_TRAVERSE,
    //Pipe Masks
    FILE_CREATE_PIPE_INSTANCE = FILE_APPEND_DATA,
}