//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapphTools.DHA.Stig.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SapphTools.DHA.Stig.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIFrTCCA5WgAwIBAgIQKlybgnwsT5ZO0W7QdSuxkTANBgkqhkiG9w0BAQsFADBp
        ///MQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQL
        ///EwNEb0QxDDAKBgNVBAsTA1BLSTEMMAoGA1UECxMDREhBMRYwFAYDVQQDEw1ESEEg
        ///Um9vdCBDQSAxMB4XDTE2MTIyODAwMzk1MloXDTQwMTIyODAwMzk1MlowaTELMAkG
        ///A1UEBhMCVVMxGDAWBgNVBAoTD1UuUy4gR292ZXJubWVudDEMMAoGA1UECxMDRG9E
        ///MQwwCgYDVQQLEwNQS0kxDDAKBgNVBAsTA0RIQTEWMBQGA1UEAxMNREhBIFJvb3Qg
        ///Q0EgMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMBQTjVoRfRIEyUK
        ///HGN7MbuX3DQAHAUew1JO5UCuCSju1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCert_21D77E4B5D18A5170CAC8926FBE89F54F9EBD041 {
            get {
                return ResourceManager.GetString("RootCert_21D77E4B5D18A5170CAC8926FBE89F54F9EBD041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIICJDCCAaqgAwIBAgIBDzAKBggqhkjOPQQDAzBbMQswCQYDVQQGEwJVUzEYMBYG
        ///A1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNEb0QxDDAKBgNVBAsTA1BL
        ///STEWMBQGA1UEAxMNRG9EIFJvb3QgQ0EgNTAeFw0xNjA2MTQxNzE3MjdaFw00MTA2
        ///MTQxNzE3MjdaMFsxCzAJBgNVBAYTAlVTMRgwFgYDVQQKEw9VLlMuIEdvdmVybm1l
        ///bnQxDDAKBgNVBAsTA0RvRDEMMAoGA1UECxMDUEtJMRYwFAYDVQQDEw1Eb0QgUm9v
        ///dCBDQSA1MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAENmLeC07Ax9cpRTp/HJnmKiF2
        ///sQDdjEf/wLG0+s46TlL7p+02LRweHJCNl6orpuLTc3N8XBzQZ/QKKdOQhOtR5fFe
        ///HMDShoTFbdEkSQ7sF4nkaMjeGlwaB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCert_4ECB5CC3095670454DA1CBD410FC921F46B8564B {
            get {
                return ResourceManager.GetString("RootCert_4ECB5CC3095670454DA1CBD410FC921F46B8564B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIDcDCCAligAwIBAgIBBTANBgkqhkiG9w0BAQUFADBbMQswCQYDVQQGEwJVUzEY
        ///MBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNEb0QxDDAKBgNVBAsT
        ///A1BLSTEWMBQGA1UEAxMNRG9EIFJvb3QgQ0EgMjAeFw0wNDEyMTMxNTAwMTBaFw0y
        ///OTEyMDUxNTAwMTBaMFsxCzAJBgNVBAYTAlVTMRgwFgYDVQQKEw9VLlMuIEdvdmVy
        ///bm1lbnQxDDAKBgNVBAsTA0RvRDEMMAoGA1UECxMDUEtJMRYwFAYDVQQDEw1Eb0Qg
        ///Um9vdCBDQSAyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwCzB9o07
        ///rP8/PNZxvrh0IgfscEEV/KtA4weqwcPYn/7aTDq/P8jYKHtLNgHArEUlw9IOCo+F
        ///GGQQPRoTcCpvjtfcjZOzQQ84Ic2tq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCert_8C941B34EA1EA6ED9AE2BC54CF687252B4C9B561 {
            get {
                return ResourceManager.GetString("RootCert_8C941B34EA1EA6ED9AE2BC54CF687252B4C9B561", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIB6zCCAY+gAwIBAgIBATAMBggqhkjOPQQDAgUAMFsxCzAJBgNVBAYTAlVTMRgw
        ///FgYDVQQKEw9VLlMuIEdvdmVybm1lbnQxDDAKBgNVBAsTA0RvRDEMMAoGA1UECxMD
        ///UEtJMRYwFAYDVQQDEw1Eb0QgUm9vdCBDQSA0MB4XDTEyMDczMDE5NDgyM1oXDTMy
        ///MDcyNTE5NDgyM1owWzELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD1UuUy4gR292ZXJu
        ///bWVudDEMMAoGA1UECxMDRG9EMQwwCgYDVQQLEwNQS0kxFjAUBgNVBAMTDURvRCBS
        ///b290IENBIDQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR2yNhDyw8H0iwPKtA4
        ///8YLNQlXn3B1agLcIkUtU1k+yZoU0lo0uPvTgSpF8zM2GnxHgUqFmgsbLkCPsX1/1
        ///8DxFo0IwQDAdBgNVHQ4EFgQUvcG5a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCert_B8269F25DBD937ECAFD4C35A9838571723F2D026 {
            get {
                return ResourceManager.GetString("RootCert_B8269F25DBD937ECAFD4C35A9838571723F2D026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIDgzCCAmugAwIBAgIBATANBgkqhkiG9w0BAQsFADBjMQswCQYDVQQGEwJVUzEY
        ///MBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNEb0QxEDAOBgNVBAsT
        ///B1dDRiBQS0kxGjAYBgNVBAMTEURvRCBXQ0YgUm9vdCBDQSAxMB4XDTE1MTEwOTE5
        ///NDczM1oXDTMwMTIzMDE5NDczM1owYzELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD1Uu
        ///Uy4gR292ZXJubWVudDEMMAoGA1UECxMDRG9EMRAwDgYDVQQLEwdXQ0YgUEtJMRow
        ///GAYDVQQDExFEb0QgV0NGIFJvb3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEP
        ///ADCCAQoCggEBAMZwONyevljnmT1CAWfoMfwR52xR4Tdiegfb1pyGU9yhB0+Xanxk
        ///oIXF6QdvP7P9IU2o86XOzX5SJ0alD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCert_CA73856F1BD280836EB7E039FB859E715F87C634 {
            get {
                return ResourceManager.GetString("RootCert_CA73856F1BD280836EB7E039FB859E715F87C634", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIFdTCCA12gAwIBAgIBATANBgkqhkiG9w0BAQwFADBbMQswCQYDVQQGEwJVUzEY
        ///MBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNEb0QxDDAKBgNVBAsT
        ///A1BLSTEWMBQGA1UEAxMNRG9EIFJvb3QgQ0EgNjAgFw0yMzAxMjQxNjM2MTdaGA8y
        ///MDUzMDEyNDE2MzYxN1owWzELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD1UuUy4gR292
        ///ZXJubWVudDEMMAoGA1UECxMDRG9EMQwwCgYDVQQLEwNQS0kxFjAUBgNVBAMTDURv
        ///RCBSb290IENBIDYwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC8qBu+
        ///0w51OkG8fw3ReHS/itcp9AEFC4ETwumtfwlS+tmxBU3ulJPATIHC/TCOg6Tksvij
        ///vwt8RJdmgOUQj1u/+PEo6C7tgBgM5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCert_D37ECF61C0B4ED88681EF3630C4E2FC787B37AEF {
            get {
                return ResourceManager.GetString("RootCert_D37ECF61C0B4ED88681EF3630C4E2FC787B37AEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIDczCCAlugAwIBAgIBATANBgkqhkiG9w0BAQsFADBbMQswCQYDVQQGEwJVUzEY
        ///MBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNEb0QxDDAKBgNVBAsT
        ///A1BLSTEWMBQGA1UEAxMNRG9EIFJvb3QgQ0EgMzAeFw0xMjAzMjAxODQ2NDFaFw0y
        ///OTEyMzAxODQ2NDFaMFsxCzAJBgNVBAYTAlVTMRgwFgYDVQQKEw9VLlMuIEdvdmVy
        ///bm1lbnQxDDAKBgNVBAsTA0RvRDEMMAoGA1UECxMDUEtJMRYwFAYDVQQDEw1Eb0Qg
        ///Um9vdCBDQSAzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqewUcoro
        ///S3Cj2hADhKb7pzYNKjpSFr8wFVKGBUcgz6qmzXXEZG7v8WAjywpmQK60yGgqAFFo
        ///STfpWTJNlbxDJ+lAjToQzhS8Qxih+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCert_D73CA91102A2204A36459ED32213B467D7CE97FB {
            get {
                return ResourceManager.GetString("RootCert_D73CA91102A2204A36459ED32213B467D7CE97FB", resourceCulture);
            }
        }
    }
}
