<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <RootNamespace>SapphTools.DHA.Stig.Common</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="SapphTools.DHA.Stig.Common.Converters" />
    <Using Include="SapphTools.DHA.Stig.Common.Enums" />
    <Using Include="SapphTools.DHA.Stig.Common.Interfaces" />
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SecurityDescriptor\SecurityDescriptor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
