// <auto-generated/>
global using SapphTools.DHA.Stig.Common;
global using SapphTools.DHA.Stig.Common.Attributes;
global using SapphTools.DHA.Stig.Common.Classes;
global using SapphTools.DHA.Stig.Common.Converters;
global using SapphTools.DHA.Stig.Common.Enums;
global using SapphTools.DHA.Stig.Common.Extensions;
global using SapphTools.DHA.Stig.Common.Interfaces;
global using SapphTools.DHA.Stig.Common.Properties;
global using SapphTools.DHA.Stig.Common.WinApi;